apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'application'

application {
    mainClass = 'com.halil.ozel.huaweimapkitapp.cli.MapKitCliKt'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:${rootProject.ext.kotlin_version}"
}
